let produtos = [
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'BRAVA/DOBLO/FIORINO',
    referencia: 'BAHB633531',
    marca: 'MTF',
    externo: '72',
    interno: '37',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'CLIO/TWINGO S/ABS',
    referencia: 'ALR12033',
    marca: 'IMA',
    externo: '65',
    interno: '35',
    altura: '35',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'CLIO/TWINGO S/ABS',
    referencia: 'GB12438/S01R',
    marca: 'SNR',
    externo: '',
    interno: '',
    altura: '',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'COROLLA 02/08 S/ABS',
    referencia: '6831',
    marca: 'YMAX',
    externo: '',
    interno: '',
    altura: '',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'COROLLA 02/08 S/ABS',
    referencia: 'GB44542T02S',
    marca: 'SNR',
    externo: '74',
    interno: '40',
    altura: '42',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'CORSA/CELTA/AGILE',
    referencia: 'BAH636114',
    marca: 'SKF',
    externo: '66',
    interno: '34',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'CORSA/CELTA/AGILE',
    referencia: 'LVB636114',
    marca: 'LUCAS',
    externo: '66',
    interno: '34',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'CORSA/CELTA/AGILE',
    referencia: 'MTF636114',
    marca: 'MTF',
    externo: '66',
    interno: '34',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'CORSA/MONTANA 02/...',
    referencia: '713188610',
    marca: 'FAG',
    externo: '67',
    interno: '34',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'CORSA/MONTANA 02/...',
    referencia: 'ALR803775',
    marca: 'IMA',
    externo: '67',
    interno: '34',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'DUSTER/FLUENCE/OROCH',
    referencia: 'XGB41793R02',
    marca: 'SNR',
    externo: '80',
    interno: '42',
    altura: '39',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'EXT RANGER/ACDS10',
    referencia: 'LM12749/710Q',
    marca: 'SKF',
    externo: '45',
    interno: '22',
    altura: '',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'EXT S10/BLAZER 95/12',
    referencia: '92649',
    marca: 'ZEN',
    externo: '50',
    interno: '21.5',
    altura: '14',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'EXT S10/BLAZER 95/12',
    referencia: 'ALR12649/10',
    marca: 'IMA',
    externo: '50',
    interno: '21.5',
    altura: '14',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'FIESTA/MONZA/GOL 95/...',
    referencia: '805589DA',
    marca: 'FAG',
    externo: '',
    interno: '',
    altura: '',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'FIESTA/MONZA/GOL 95/...',
    referencia: '90206',
    marca: 'ZEN',
    externo: '72',
    interno: '39',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'FIESTA/MONZA/GOL 95/...',
    referencia: 'ALR0036',
    marca: 'IMA',
    externo: '72',
    interno: '39',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'FIESTA/MONZA/GOL 95/...',
    referencia: 'BAH0206',
    marca: 'SKF',
    externo: '72',
    interno: '39',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'FIESTA/MONZA/GOL 95/...',
    referencia: 'LVB0036',
    marca: 'LUCAS',
    externo: '72',
    interno: '39',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'GOL .../94',
    referencia: 'ARL311315',
    marca: 'IMA',
    externo: '68',
    interno: '39',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'GOL .../94',
    referencia: 'HNZ91315',
    marca: 'ZEN',
    externo: '68',
    interno: '39',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'GOL .../94',
    referencia: 'LVB311315',
    marca: 'LUCAS',
    externo: '68',
    interno: '39',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'GOLF 1.6/2.0 99/',
    referencia: '801136',
    marca: 'FAG',
    externo: '74',
    interno: '40',
    altura: '40',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'GOLF 1.6/2.0 99/',
    referencia: 'IRB10212',
    marca: 'IRB',
    externo: '74',
    interno: '40',
    altura: '40',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'GOLF/BORA 97/...',
    referencia: '443B',
    marca: 'YMAX',
    externo: '72',
    interno: '40',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'INT RANGER/ACDS10/F1000',
    referencia: '4854810',
    marca: 'VTO',
    externo: '65',
    interno: '35',
    altura: '',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'INT RANGER/ACDS10/F1000',
    referencia: 'ALR4854810',
    marca: 'IMA',
    externo: '65',
    interno: '35',
    altura: '',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'INT S10/BLAZER 95/12',
    referencia: 'ALR67048/10',
    marca: 'IMA',
    externo: '59',
    interno: '32',
    altura: '12',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'INT S10/BLAZER 95/12',
    referencia: 'HNZ97048',
    marca: 'ZEN',
    externo: '59',
    interno: '32',
    altura: '12',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'INT S10/BLAZER 95/12',
    referencia: 'LM67048/010',
    marca: 'SKF',
    externo: '59',
    interno: '32',
    altura: '12',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'NEW KA/ECOSPORT/G5',
    referencia: 'ALR0106',
    marca: 'IMA',
    externo: '72',
    interno: '39',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'NEW KA/ECOSPORT/G5',
    referencia: 'VKBC4220',
    marca: 'SKF',
    externo: '72',
    interno: '39',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'NV PALIO/UNO/GRAND SIEN',
    referencia: 'VKBC3577',
    marca: 'SKF',
    externo: '66',
    interno: '35',
    altura: '33',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'NV PALIO/UNO/GRAND SIENA',
    referencia: 'ALR0015',
    marca: 'IMA',
    externo: '66',
    interno: '35',
    altura: '33',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'ONIX/COBALT/PRISMA',
    referencia: 'ALR4078ABS',
    marca: 'IMA',
    externo: '78',
    interno: '40',
    altura: '40',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'ONIX/COBALT/PRISMA',
    referencia: 'VKBC4219',
    marca: 'SKF',
    externo: '78',
    interno: '40',
    altura: '40',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'PALIO/DOBLO/CLIO/SANDER',
    referencia: 'LVB0094',
    marca: 'LUCAS',
    externo: '72',
    interno: '37',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'PALIO/DOBLO/CLIO/SANDER',
    referencia: 'VKBC4221',
    marca: 'SKF',
    externo: '72',
    interno: '37',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'PALIO/DOBLO/CLIO/SANDERO',
    referencia: 'GB1280S',
    marca: 'SNR',
    externo: '72',
    interno: '37',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'PUNTO 1.4/1.6 S/ABS',
    referencia: 'ALR0013',
    marca: 'IMA',
    externo: '72',
    interno: '35',
    altura: '33',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'PUNTO/LINEA S/ABS',
    referencia: 'VKBC20017',
    marca: 'SKF',
    externo: '72',
    interno: '35',
    altura: '33',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'STRADA/DOBLO/PUNTO C/ABS',
    referencia: 'VKBC3539',
    marca: 'SKF',
    externo: '72',
    interno: '37',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'UNO/PALIO/SIENA',
    referencia: '50002',
    marca: 'SCHADEK',
    externo: '68',
    interno: '35',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'UNO/PALIO/SIENA',
    referencia: '90031',
    marca: 'ZEN',
    externo: '68',
    interno: '35',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'UNO/PALIO/SIENA',
    referencia: 'MTF633967',
    marca: 'MTF',
    externo: '68',
    interno: '35',
    altura: '37',
  },
  {
    dtts: 'DT',
    rodaRigido: 'RODA',
    descricao: 'KIT ROLAMENTO DT KOMBI 75/14 ',
    referencia: 'ALK4578',
    marca: 'IMA',
    externo: 'maior 57 menor 45',
    interno: 'maior 32 menor 19',
    altura: '13',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'CORSA/CELTA/KADETT',
    referencia: 'ALK4544',
    marca: 'IMA',
    externo: 'menor 40, maior 50',
    interno: 'menor 17, maior 29',
    altura: '15',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'CORSA/CELTA/KADETT',
    referencia: 'MTF2271',
    marca: 'MTF',
    externo: 'maior 50, menor 40',
    interno: 'maior 29, menor 12',
    altura: '15',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'CORSA/CELTA/KADETT',
    referencia: 'R15307S',
    marca: 'NTN',
    externo: '',
    interno: '',
    altura: '',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'CORSA/CELTA/KADETT',
    referencia: 'VKBA4544A',
    marca: 'SKF',
    externo: 'menor 40,maior 50',
    interno: 'menor 17,maior 29',
    altura: '15',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'GOL/SAVEIRO',
    referencia: 'R15413S',
    marca: 'SNR',
    externo: '',
    interno: '',
    altura: '',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'GOL/SAVEIRO',
    referencia: 'VK0004TV',
    marca: 'VETOR',
    externo: 'maior 50, menor 40',
    interno: 'maior 29, menor 17',
    altura: '11',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'GOL/SAVEIRO',
    referencia: 'VKBA4529A',
    marca: 'SKF',
    externo: 'maior 50, menor 40',
    interno: 'maior 29, menor 17',
    altura: '11',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'KA/FIESTA/ESCORT 93/...',
    referencia: '94533',
    marca: 'ZEN',
    externo: 'maior 50, menor 50',
    interno: 'maior 29, menor 29',
    altura: '11',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'KA/FIESTA/ESCORT 93/...',
    referencia: 'IRB400',
    marca: 'IRB',
    externo: '',
    interno: '',
    altura: '',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'KA/FIESTA/ESCORT 93/... (kit)',
    referencia: 'VKBA4533',
    marca: 'SKF',
    externo: '50',
    interno: '29',
    altura: '18',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'SPRINTER/BLAZER/S10',
    referencia: 'U399/360',
    marca: 'SKF',
    externo: '73',
    interno: '40',
    altura: '18.5',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'SPRINTER/BLAZER/S10',
    referencia: 'U497/460L',
    marca: 'SKF',
    externo: '80',
    interno: '45',
    altura: '22',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'CLIO/LOGAN/C3/206 99/12',
    referencia: 'LVB445539',
    marca: 'LUCAS',
    externo: '',
    interno: '',
    altura: '',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'CLIO/LOGAN/C3/206 ALR',
    referencia: '40570E',
    marca: 'IMA',
    externo: '52',
    interno: '25',
    altura: '37',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'CORSA 02/...',
    referencia: 'FC40650S01R',
    marca: 'SNR',
    externo: '',
    interno: '',
    altura: '',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'CORSA/MERIVA 02/...',
    referencia: 'ALR40650',
    marca: 'IMA',
    externo: '53',
    interno: '27',
    altura: '43',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'EXT KOMBI 78/14',
    referencia: 'LVB45226',
    marca: 'LUCAS',
    externo: '62',
    interno: '35',
    altura: '19',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'FIESTA/ECOSPORT/FOCUS',
    referencia: 'ALR1206',
    marca: 'IMA',
    externo: '',
    interno: '',
    altura: '',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'FIESTA/ECOSPORT/FOCUS',
    referencia: 'IR18206',
    marca: 'IRB',
    externo: '53',
    interno: '29',
    altura: '37',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'FIESTA/ECOSPORT/FOCUS',
    referencia: 'LVB0095',
    marca: 'LUCAS',
    externo: '53',
    interno: '29',
    altura: '37',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'DUSTER/CAPTUR/207',
    referencia: 'FC40696S12R',
    marca: 'SNR',
    externo: '62',
    interno: '30',
    altura: '48',
  },
  {
    dtts: 'TS',
    rodaRigido: 'RODA',
    descricao: 'LOGAN/SANDERO 14/',
    referencia: 'FC41795S01R',
    marca: 'SNR',
    externo: '55',
    interno: '25',
    altura: '43',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6000-2Z',
    marca: 'SKF',
    externo: '26',
    interno: '10',
    altura: '8',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6001-2Z',
    marca: 'Não Cadastrado',
    externo: '28',
    interno: '12',
    altura: '8',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6002-2Z',
    marca: 'SKF',
    externo: '32',
    interno: '15',
    altura: '9',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6003.2RSR.A4',
    marca: 'FAG',
    externo: '35',
    interno: '17',
    altura: '10',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6003-2RSR',
    marca: 'SKF',
    externo: '35',
    interno: '17',
    altura: '10',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '608-2RSH',
    marca: 'SKF',
    externo: '22',
    interno: '8',
    altura: '7',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '608-2Z',
    marca: 'SKF',
    externo: '22',
    interno: '8',
    altura: '7',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6200-2Z',
    marca: 'SKF',
    externo: '30',
    interno: '10',
    altura: '9',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6201-2RS',
    marca: 'IRB',
    externo: '32',
    interno: '12',
    altura: '10',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6201-2Z',
    marca: 'SKF',
    externo: '32',
    interno: '12',
    altura: '10',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6201-2Z/C3',
    marca: 'SKF',
    externo: '32',
    interno: '12',
    altura: '10',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6202.2RSR.A4',
    marca: 'FAG',
    externo: '35',
    interno: '15',
    altura: '11',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6202.2ZR.A4',
    marca: 'FAG',
    externo: '35',
    interno: '15',
    altura: '11',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6202-2RSR-2',
    marca: 'SKF',
    externo: '35',
    interno: '15',
    altura: '11',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6202-2Z',
    marca: 'SKF',
    externo: '35',
    interno: '15',
    altura: '11',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6203.2RSR',
    marca: 'FAG',
    externo: '40',
    interno: '17',
    altura: '12',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6203-2RSH',
    marca: 'SKF',
    externo: '40',
    interno: '17',
    altura: '12',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6203-2Z',
    marca: 'SKF',
    externo: '40',
    interno: '17',
    altura: '12',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6204.2RSRC3',
    marca: 'FAG',
    externo: '47',
    interno: '20',
    altura: '14',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6204-2RS',
    marca: 'IRB',
    externo: '47',
    interno: '20',
    altura: '14',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6204-2RSH/C3GJN',
    marca: 'SKF',
    externo: '47',
    interno: '20',
    altura: '14',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6204-2Z',
    marca: 'SKF',
    externo: '47',
    interno: '20',
    altura: '14',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6205.2Z',
    marca: 'SKF',
    externo: '52',
    interno: '25',
    altura: '15',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6301-2Z',
    marca: 'SKF',
    externo: '37',
    interno: '12',
    altura: '12',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6301-2ZR',
    marca: 'FAG',
    externo: '37',
    interno: '12',
    altura: '12',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6302-2Z-I',
    marca: 'SKF',
    externo: '42',
    interno: '15',
    altura: '13',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6302Z',
    marca: 'SKF',
    externo: '42',
    interno: '15',
    altura: '13',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6303.2RSR.A4',
    marca: 'FAG',
    externo: '47',
    interno: '17',
    altura: '14',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6303-2RSH/GJN',
    marca: 'SKF',
    externo: '47',
    interno: '17',
    altura: '14',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6303-2Z/C3GJN',
    marca: 'SKF',
    externo: '47',
    interno: '17',
    altura: '14',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO RIGIDO ESFERICO',
    referencia: '6306-2RS1',
    marca: 'SKF',
    externo: '72',
    interno: '30',
    altura: '19',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO SEMI-ARVORE SEMIEIXO 1.8 GM',
    referencia: '63006-2RS1',
    marca: 'SKF',
    externo: '55',
    interno: '30',
    altura: '19',
  },
  {
    dtts: '#',
    rodaRigido: 'RIGIDO',
    descricao: 'ROLAMENTO SEMI-ARVORE SEMIEIXO 1.8 GM',
    referencia: 'ALR63006-2RSC3',
    marca: 'IMA',
    externo: '55',
    interno: '30',
    altura: '19',
  },
  
]