const produtos = [
  {
    descricao: 'AGILE/ASTRA/ZAFIRA/MONZA/STRADA',
    referencia: '149/4',
    marca: '',
    arqImagem: '',
    linksExternos: [{url:'',titulo:''}],
  },
  {
    descricao: 'AGILE/ASTRA/ZAFIRA/MONZA/STRADA ',
    referencia: 'A149',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a149.jpg',
    linksExternos: [{url:'sulcarbon-a149.pdf',titulo:'SULCARBON pdf'}],
  },
  {
    descricao: 'ASTRA/BLAZER/S10/ZAFIRA/MONZA ',
    referencia: 'A193',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a193.jpeg',
    linksExternos: [{url:'sulcarbon-a193.pdf',titulo:'SULCARBON PDF'}],
  },
  {
    descricao: 'CORSA/GOL/FUSCA/KOMBI',
    referencia: '1.116/4',
    marca: '',
    arqImagem: '',
    linksExternos: [{url:'',titulo:''}],
  },
  {
    descricao: 'CORSA/GOL/FUSCA/KOMBI (mais comum)',
    referencia: 'A116',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a116.png',
    linksExternos: [{url:'sulcarbon-a116.pdf',titulo:'SULCARBON PDF'}],
  },
  {
    descricao: 'CORSA/GOL/FUSCA/KOMBI/CLIO ',
    referencia: '1.128/4',
    marca: 'UNIFAP',
    arqImagem: 'unifap-1-1284.jpeg',
    linksExternos: [{url:'https://unifap.com.br/pt/produtos/1-128-4/?hilite=11284',titulo:'UNIFAP'}],
  },
  {
    descricao: 'FIAT/FORD/GM ',
    referencia: 'A101',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a101.png',
    linksExternos: [{url:'sulcarbon-a101.pdf',titulo:'SULCARBON PDF'}],
  },
  {
    descricao: 'GOLF/POLO/FOX/ECOSPORT ',
    referencia: 'A203',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a203.jpeg',
    linksExternos: [{url:'sulcarbon-a203.pdf',titulo:'SULCARBON PDF'}],
  },
  {
    descricao: 'GOLF/POLO/FOX/ECOSPORT ',
    referencia: '1203/4',
    marca: 'UNIFAP',
    arqImagem: 'sulcarbon-a203.jpeg',
    linksExternos: [{url:'https://unifap.com.br/pt/produtos/1-203-4/?hilite=12034',titulo:'UNIFAP'}],
  },
  {
    descricao: 'PALIO/STILO/ASTRA/CLIO/206 ',
    referencia: '594351',
    marca: 'VALEO',
    arqImagem: 'valeo-594351.png',
    linksExternos: [{url:'https://catalogoexpresso.com.br/valeo/detalhes?cw_filtros=PCs%3C!2!%3E594351%3C!TAB!%3E&cw_ordenacao=cw-ordena-lancamento&cw_ie_tp=0&cw_produtoAtivo=CodigoProduto%3C!2!%3E17810',titulo:'VALEO'}],
  },
  {
    descricao: 'PALIO/STILO/ASTRA/CLIO/206 ',
    referencia: 'A171',
    marca: '',
    arqImagem: 'valeo-594351.png',
    linksExternos: [{url:'sulcarbon-a171.pdf',titulo:'SULCARBON PDF'}],
  },
  {
    descricao: 'PALIO/STRADA/STILO/DOBLO ',
    referencia: '141/4',
    marca: '',
    arqImagem: '',
    linksExternos: [{url:'',titulo:''}],
  },
  {
    descricao: 'PALIO/STRADA/STILO/DOBLO ',
    referencia: 'A141',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a141.jpg',
    linksExternos: [{url:'sulcarbon-a141.pdf',titulo:'SULCARBON PDF'}],
  },
  {
    descricao: 'PALIO/UNO/LINEA/GOLF/A3 ',
    referencia: '1.222/4',
    marca: 'UNIFAP',
    arqImagem: 'sulcarbon-a222.jpg',
    linksExternos: [{url:'https://unifap.com.br/pt/produtos/1-222-4/',titulo:'UNIFAP'}],
  },
  {
    descricao: 'PALIO/UNO/LINEA/GOLF/A3 ',
    referencia: 'A222',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a222.jpg',
    linksExternos: [{url:'sulcarbon-a222.pdf',titulo:'SULCARBON PDF'}],
  },
  {
    descricao: 'PALIO/UNO/LINEA/GOLF/A3 ',
    referencia: 'IK1040',
    marca: '',
    arqImagem: '',
    linksExternos: [{url:'',titulo:''}],
  },
  {
    descricao: 'STRADA/PUNTO/GOL ',
    referencia: '1210/4',
    marca: 'UNIFAP',
    arqImagem: '12104-UNIFAP.jpg',
    linksExternos: [{url:'https://unifap.com.br/pt/produtos/1-210-4/',titulo:'UNIFAP'}],
  },
  {
    descricao: 'STRADA/PUNTO/GOL ',
    referencia: 'A210',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a210.jpg',
    linksExternos: [{url:'sulcarbon-a210.pdf',titulo:'SULCARBON PDF'}],
  },
  {
    descricao: 'UNO/FIORINO/PALIO/STRADA ',
    referencia: 'A140',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a140.png',
    linksExternos: [{url:'sulcarbon-a140.pdf',titulo:'SULCARBON PDF'}],
  },
  {
    descricao: 'UNO/PALIO 98/... ',
    referencia: 'A219',
    marca: 'SULCARBON',
    arqImagem: 'sulcarbon-a219.jpg',
    linksExternos: [{url:'sulcarbon-a219.pdf',titulo:'SULCARBON PDF'}],
  },  
]
