let produtos = [
  {
    descricao: 'CELTA/CORSA/CLIO ',
    referencia: 'ZEN1064 ',
    dentesSuperior: '8',
    dentesInferior: '5',
    diametroFuro: '11',
    altura: '41',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'zen1064.jpg' 
  },
  {
    descricao: 'CELTA/CORSA/CLIO/KANGOO ',
    referencia: 'BZM0843 ',
    dentesSuperior: '8',
    dentesInferior: '5',
    diametroFuro: '11',
    altura: '44',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'bzm843.jpg'
  },
  {
    descricao: 'ASTRA/MERIVA/PALIO/DOBLO',
    referencia: 'ZE10003 ',
    dentesSuperior: '9',
    dentesInferior: '6',
    diametroFuro: '12',
    altura: '47',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'BZM09521.jpg'
  },
  {
    descricao: 'ASTRA/MERIVA/PALIO/DOBLO',
    referencia: 'BZM09521',
    dentesSuperior: '9',
    dentesInferior: '6',
    diametroFuro: '12',
    altura: '47',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'BZM09521.jpg'
  },
  {
    descricao: 'CHEVETT/SANT/GOL/ESCORT ',
    referencia: 'BZM0108 ',
    dentesSuperior: '',
    dentesInferior: '',
    diametroFuro: '',
    altura: '',
    largura: '',
    marca: 'BZM',
    arqImagem: ''
  },
  {
    descricao: 'CHEVETT/SANT/GOL/ESCORT ',
    referencia: 'ZE0108 ',
    dentesSuperior: '9',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '64',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'zen108.png'
  },
  {
    descricao: 'CORSA/UNO ',
    referencia: 'BZM0837 ',
    dentesSuperior: '9',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '59',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'bzm837.png'
  },
  {
    descricao: 'CORSA/UNO ',
    referencia: 'ZEN0837 ',
    dentesSuperior: '9',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '59',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'zen837.avif'
  },
  {
    descricao: 'ESCORT/VERONA/GOLF/POLO ',
    referencia: 'ZEN0729 ',
    dentesSuperior: '10',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '77',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'zen729.jpg'
  },
  {
    descricao: 'FIESTA/COURIER/KA/LOGAN ',
    referencia: 'ZE1686 ',
    dentesSuperior: '9',
    dentesInferior: '4',
    diametroFuro: '10',
    altura: '41',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'zen1686.jpeg'
  },
  {
    descricao: 'GOL/KOMBI/FUSCA/SAVEIRO ',
    referencia: 'BZM0065 ',
    dentesSuperior: '9',
    dentesInferior: '10',
    diametroFuro: '11',
    altura: '62',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'bzm065.jpg'
  },
  {
    descricao: 'GOL/KOMBI/FUSCA/SAVEIRO ',
    referencia: 'HNZ0065 ',
    dentesSuperior: '9',
    dentesInferior: '10',
    diametroFuro: '11',
    altura: '63',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'zen0065.jpg'
  },
  {
    descricao: 'GOL/PARATI AP 02/... ',
    referencia: 'BZM1177 ',
    dentesSuperior: '9',
    dentesInferior: '16',
    diametroFuro: '13',
    altura: '91',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'bzm1177.png'
  },
  {
    descricao: 'GOL/PARATI MI ',
    referencia: 'BZM0933 ',
    dentesSuperior: '10',
    dentesInferior: '16',
    diametroFuro: '11',
    altura: '90',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'BZM0933.jpeg'
  },
  {
    descricao: 'GOL/PARATI/SAVEIRO AP/MI ',
    referencia: 'ZEN0942',
    dentesSuperior: '9',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '62',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'ZEN0942.jpg'
  },
  {
    descricao: 'GOL/PASSAT/VOY/SAV/PARAT ',
    referencia: '0068 ',
    dentesSuperior: '9',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '64',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'zen0068.jpg'
  },
  {
    descricao: 'GOLF/GOL G5 10/... ',
    referencia: 'BZM1712 ',
    dentesSuperior: '9',
    dentesInferior: '11',
    diametroFuro: '14',
    altura: '83',
    largura: '45',
    marca: 'BZM',
    arqImagem: 'bzm1712.jpg'
  },
  {
    descricao: 'KA/FIESTA/ECOSPORT ',
    referencia: 'ZEN1533 ',
    dentesSuperior: '9',
    dentesInferior: '10',
    diametroFuro: '11',
    altura: '41',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'zen1686.jpeg'
  },
  {
    descricao: 'PASSAT/SANTANA/PARATI ',
    referencia: 'BZM008660 ',
    dentesSuperior: '9',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '61',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'bzm866.png'
  },
  {
    descricao: 'PASSAT/SANTANA/PARATI ',
    referencia: 'ZE0866 ',
    dentesSuperior: '',
    dentesInferior: '',
    diametroFuro: '',
    altura: '',
    largura: '',
    marca: 'ZEN',
    arqImagem: ''
  },
  {
    descricao: 'RANGER/F1000 DIESEL ',
    referencia: 'BZM0941 ',
    dentesSuperior: '9',
    dentesInferior: '12',
    diametroFuro: '12',
    altura: '59',
    largura: '48.5',
    marca: 'BZM',
    arqImagem: 'bzm941.jpg'
  },
  {
    descricao: 'UNO FIRE ',
    referencia: 'BZM0786 ',
    dentesSuperior: '9',
    dentesInferior: '6',
    diametroFuro: '12',
    altura: '64',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'bzm786.png'
  },
  {
    descricao: 'UNO MILLE/PALIO/SIENA 96/ ',
    referencia: 'BZM0846 ',
    dentesSuperior: '11',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '59',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'BZM0846.jpeg'
  },
  {
    descricao: 'UNO MILLE/PALIO/SIENA 96/ ',
    referencia: 'ZE0846 ',
    dentesSuperior: '11',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '59',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'BZM0846.jpeg'
  },
  {
    descricao: 'UNO/PALIO/DOBLO/STRADA ',
    referencia: 'ZEN1666 ',
    dentesSuperior: '9',
    dentesInferior: '11',
    diametroFuro: '10',
    altura: '49',
    largura: '45',
    marca: 'ZEN',
    arqImagem: 'zen1666.jpg'
  },
  {
    descricao: 'UNO/PREMIO/ELBA/FIORINO ',
    referencia: 'ZEN0111 ',
    dentesSuperior: '11',
    dentesInferior: '10',
    diametroFuro: '12', 
    altura: '64',
    largura: '46',
    marca: 'ZEN',
    arqImagem: 'bzm111.png'
  },
  {
    descricao: 'UNO/PREMIO/ELBA/FIORINO ',
    referencia: 'BZM1110 ',
    dentesSuperior: '11',
    dentesInferior: '10',
    diametroFuro: '12',
    altura: '64',
    largura: '46',
    marca: 'BZM',
    arqImagem: 'bzm111.png'
  },
  {
    descricao: 'FOX/GOL/GOLF/POLO/VOYAGE ',
    referencia: 'HNZ1893 ',
    dentesSuperior: '11',
    dentesInferior: '4',
    diametroFuro: 'é tapado',
    altura: '81',
    largura: '49.5',
    marca: 'BZM',
    arqImagem: 'zen1893.jpg'
  },
]