const cadastroMontadoras = {
  1: "Volkswagen",
  2: "Toyota",
  3: "Renault",
  4: "Peugeot",
  5: "Nissan",
  6: "Mercedes-Benz",
  7: "Kia",
  8: "Jeep", 
  9: "Honda",
  10: "Ford",
  11: "FIAT",
  12: "Citroen",
  13: "Chevrolet",
  14: "BYD",
  15: "BMW",
  16: "Audi",
  17: "Mitsubishi",
  18: "Land Rover",
  19: "DAEWOO",
  20: "CHRYSLER",
  21: "Chery",
  22: "Hyundai",
  23: "Alfa Romeo",
  24: "Seat",
  25: "Troller",
  26: "Lada",
  27: "Ferrari",
}            