const produtos = [
  {
    tipo: 'HOMOCINETICA',
    desc: 'UNO/FIORINO/PREMIO 84/96',
    referencia: 'JHC03103',
    marca: 'COFAP',
    int: '20',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'aplicacoes/JHC03103.txt',titulo:'arquivo de texto'}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'UNO/FIORINO/PREMIO 84/96',
    referencia: '6003',
    marca: 'AXIOS',
    int: '20',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'SIENA/PALIO/WEEKEND',
    referencia: 'JHC03123',
    marca: 'COFAP',
    int: '20',
    ext: '22',
    diamParaf: '22',
    trava: 'EXTERNA C',
    linksExternos: [{url:'aplicacoes/JHC03123.txt',titulo:'arquivo de texto'},
      {url:'https://loja.cofap.com.br/p/1077506/junta-homocinetica-fixa-dianteira-lado-roda-cofap-jhc03123-unitario',titulo:'COFAP'}
    ],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'SIENA/PALIO/WEEKEND   ',
    referencia: '6008',
    marca: 'AXIOS',
    int: '20',
    ext: '22',
    diamParaf: '22',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'PALIO/UNO/FIORINO 96/12   ',
    referencia: 'W4H37',
    marca: 'W4',
    int: '20',
    ext: '20',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'PALIO/UNO/FIORINO 96/12   ',
    referencia: 'JHC03117',
    marca: 'COFAP',
    int: '20',
    ext: '22',
    diamParaf: '22',
    trava: 'EXTERNA C',
    linksExternos: [{url:'aplicacoes/JHC03117.txt',titulo:'arquivo de texto'},
      {url:'https://loja.cofap.com.br/p/1077505/junta-homocinetica-fixa-dianteira-lado-roda-cofap-jhc03117-unitario',titulo:'COFAP'}
    ],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'ONIX/PRISMA 1.0   ',
    referencia: 'JHC04111',
    marca: 'COFAP',
    int: '20',
    ext: '25',
    diamParaf: '24',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'ONIX 1.4 S/ABS   ',
    referencia: 'W4H95',
    marca: 'W4',
    int: '20',
    ext: '25',
    diamParaf: '24',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'ONIX/COBALT 1.4 ',
    referencia: 'JHC04112',
    marca: 'COFAP',
    int: '22',
    ext: '25',
    diamParaf: '24',
    trava: 'INTERNA O',
    linksExternos: [{url:'https://loja.cofap.com.br/p/6484320/junta-homocinetica-fixa-dianteira-lado-roda-cofap-jhc04112-unitario#',titulo:'COFAP'}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'FIESTA/ECOSPORT/KA/COURIE 1.0   ',
    referencia: 'JHC08109',
    marca: 'COFAP',
    int: '20',
    ext: '25',
    diamParaf: '22',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'IDEA 1.4 03/14   ',
    referencia: 'JHC03106',
    marca: 'COFAP',
    int: '21',
    ext: '22',
    diamParaf: '22',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'UNO VIVACE/PALIO/MOBI 1.0   ',
    referencia: 'JHC03108',
    marca: 'COFAP',
    int: '21',
    ext: '22',
    diamParaf: '22',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'IDEA FIRE 1.4   ',
    referencia: 'W4H97',
    marca: 'W4',
    int: '21',
    ext: '22',
    diamParaf: '22',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'FIESTA/ECOSPORT/KA/COURIER 1.6 ',
    referencia: 'JHC08111',
    marca: 'COFAP',
    int: '21',
    ext: '25',
    diamParaf: '22',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'FIESTA/ECOSPORT/KA/COURIER 1.6 ',
    referencia: '41012A',
    marca: 'SKF',
    int: '21',
    ext: '25',
    diamParaf: '22',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'AGILE 09/13 S/ABS   ',
    referencia: 'BR10054606047',
    marca: 'AXIOS',
    int: '21',
    ext: '22',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'AGILE 09/13 C/ABS   ',
    referencia: 'M4LT30208',
    marca: 'AXIOS',
    int: '21',
    ext: '22',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'imagens/malt30208.jpg',titulo:'imagem'}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'ONIX/COBALT 1.4 13/16   ',
    referencia: '6067',
    marca: 'AXIOS',
    int: '22',
    ext: '25',
    diamParaf: '24',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'UNO VIVACE/PALIO/GRAND SIENA  ',
    referencia: 'VKJA41134A',
    marca: 'SKF',
    int: '22',
    ext: '22',
    diamParaf: '22',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'UNO VIVACE/PALIO/GRAND SIENA   ',
    referencia: 'NJH211409',
    marca: 'NAKATA',
    int: '22',
    ext: '22',
    diamParaf: '22',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' STRADA 1.4 TRAVA EMBAIXO   ',
    referencia: 'JHC03128',
    marca: 'COFAP',
    int: '22',
    ext: '22',
    diamParaf: '22',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'STRADA 1.3/1.4 TRAVA EM CIMA   ',
    referencia: 'JHC03122',
    marca: 'COFAP',
    int: '22',
    ext: '22',
    diamParaf: '22',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'STRADA 1.3/1.4 TRAVA EM CIMA ',
    referencia: 'VKJA41013',
    marca: 'SKF',
    int: '22',
    ext: '22',
    diamParaf: '22',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' STRADA 1.3/1.4 20/...   ',
    referencia: 'KJH0141',
    marca: 'PERFECT',
    int: '22',
    ext: '22',
    diamParaf: '22',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOL G5/VOYAGE/FOX 1.0   ',
    referencia: 'JHC01115',
    marca: 'COFAP',
    int: '22',
    ext: '22',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' CELTA/CORSA CLASSIC 22D   ',
    referencia: 'JHC04110',
    marca: 'COFAP',
    int: '22',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' CELTA/CORSA CLASSIC 22D   ',
    referencia: '5466058',
    marca: 'AXIOS',
    int: '22',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' CORSA/MERIVA/MONTANA   MODELO1',
    referencia: '6024',
    marca: 'AXIOS',
    int: '23',
    ext: '22',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'CORSA/MERIVA/MONTANA MODELO1',
    referencia: 'CH220',
    marca: 'VOLDA',
    int: '23',
    ext: '22',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' CORSA/MERIVA/MONTANA MODELO2',
    referencia: 'JHC04118',
    marca: 'COFAP',
    int: '23',
    ext: '22',
    diamParaf: '20',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' CORSA/MERIVA/MONTANA   MODELO2',
    referencia: 'BR10054606018',
    marca: 'AXIOS',
    int: '23',
    ext: '22',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GRAND SIENA 1.4 S/ABS   ',
    referencia: 'W4H96',
    marca: 'W4',
    int: '24',
    ext: '25',
    diamParaf: '24',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOL/VOYAGE/SPACEFOX G5 1.6   ',
    referencia: 'KJH0248',
    marca: 'PERFECT',
    int: '24',
    ext: '22',
    diamParaf: '20',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOL/VOYAGE/SPACEFOX G5 1.6   ',
    referencia: 'JHC01107',
    marca: 'COFAP',
    int: '24',
    ext: '22',
    diamParaf: '20',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' DOBLO/IDEA/SIENA/STRADA 1.8   ',
    referencia: 'JHC03127',
    marca: 'COFAP',
    int: '24',
    ext: '25',
    diamParaf: '24',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' DOBLO/IDEA/SIENA/STRADA 1.8 ',
    referencia: 'BR10054606011',
    marca: 'AXIOS',
    int: '24',
    ext: '25',
    diamParaf: '24',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' COROLLA 2.0 16V AUT 11/17   ',
    referencia: 'JHC22006',
    marca: 'COFAP',
    int: '24',
    ext: '26',
    diamParaf: '22',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' ARGO/GRAND SIENA/PUNTO/STILO   ',
    referencia: 'KJH0123',
    marca: 'PERFECT & W4',
    int: '24',
    ext: '25',
    diamParaf: '24',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' IPANEMA/MONZA/KADETT  ',
    referencia: 'JHC04101',
    marca: 'COFAP',
    int: '25',
    ext: '33',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' DOBLO/IDEA/STRADA ADV   ',
    referencia: 'JHC03104',
    marca: 'COFAP',
    int: '25',
    ext: '27',
    diamParaf: '24',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' ASTRA/ZAFIRA   ',
    referencia: 'JHC04115',
    marca: 'COFAP',
    int: '25',
    ext: '33',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' PUNTO 1.4   ',
    referencia: 'JHC03115',
    marca: 'COFAP',
    int: '28',
    ext: '22',
    diamParaf: '22',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOL/PARATI 97/08   ',
    referencia: 'JHC01112',
    marca: 'COFAP',
    int: '28',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOL/PARATI 1.0   ',
    referencia: 'KJH0253',
    marca: 'PERFECT',
    int: '28',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' CELTA/CORSA CLASSIC 28D   ',
    referencia: 'KJH9700',
    marca: 'PERFECT',
    int: '28',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' CELTA/CORSA CLASSIC 28D   ',
    referencia: 'JHC04119',
    marca: 'COFAP',
    int: '28',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' POLO/FOX 1.6/2.0 S/ABS   ',
    referencia: 'JHC01109',
    marca: 'COFAP',
    int: '30',
    ext: '22',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' POLO/FOX 1.6/2.0 C/ABS   ',
    referencia: 'JHC01106',
    marca: 'COFAP',
    int: '30',
    ext: '36',
    diamParaf: '16',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOLF/POLO 2.0    ',
    referencia: '6051',
    marca: 'AXIOS',
    int: '30',
    ext: '22',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOLF/A3 1.6    ',
    referencia: '5466049',
    marca: 'AXIOS',
    int: '30',
    ext: '36',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOL AP/MI S/TRAVA   ',
    referencia: 'JHC01105',
    marca: 'COFAP',
    int: '30',
    ext: '22',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOL AP C/TRAVA ',
    referencia: 'NJH25-129  ',
    marca: 'NAKATA',
    int: '30',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' GOL AP C/TRAVA   ',
    referencia: '6017',
    marca: 'AXIOS',
    int: '30',
    ext: '22',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: ' CLIO 1.0/1.6 00/16   ',
    referencia: 'KJH0110',
    marca: 'PERFECT',
    int: '30',
    ext: '21',
    diamParaf: '20',
    trava: 'EXTERNA C',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'LOGAN/SANDERO 08/ 21DI/23DE',
    referencia: 'JHC18111',
    marca: 'COFAP',
    int: '21',
    ext: '23',
    diamParaf: '20',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'LOGAN/SANDERO 08/ 28DI/21DE',
    referencia: 'JHC18112',
    marca: 'COFAP',
    int: '28',
    ext: '21',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'LOGAN/SANDERO 14/ L/E',
    referencia: 'JHC18113',
    marca: 'COFAP',
    int: '28',
    ext: '23',
    diamParaf: '20',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'LOGAN/SANDERO 14/ L/E ',
    referencia: 'JHC18114',
    marca: 'COFAP',
    int: '21',
    ext: '23',
    diamParaf: '20',
    trava: 'CENTRAL O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'SPIN/SONIC/COBALT/ONIX 1.4/1.8 ',
    referencia: 'JHC4123',
    marca: 'COFAP',
    int: '23',
    ext: '25',
    diamParaf: '24',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'TUCSON 04/15 ',
    referencia: '5466072',
    marca: 'AXIOS',
    int: '25',
    ext: '27',
    diamParaf: '22',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'HOMOCINETICA',
    desc: 'COBALT 1.4 MANUAL ',
    referencia: 'JHC04120',
    marca: 'COFAP',
    int: '21',
    ext: '25',
    diamParaf: '24',
    trava: 'INTERNA O',
    linksExternos: [{url:'',titulo:''}],
    arqImagem: '',
  },
  {
    tipo: 'DESLIZANTE',
    desc: 'GOL AP 82/09 33D ',
    referencia: 'JDC01304',
    marca: 'COFAP',
    int: '33',
    ext: '#',
    diamParaf: '#',
    trava: '#',
    linksExternos: [{url:'https://loja.cofap.com.br/p/1346520/junta-homocinetica-deslizante-dianteira-cofap-jdc01304-unitario',titulo:'COFAP'}]
  }
]
