let produtos = [
  {
    cambioDirecao: 'DIRECAO',
    descricao: 'BUCHA CX DIREÇÃO PALIO ',
    referencia: '10120',
    marca: 'KIT & CIA',
    arqImagem: '10120.jpg',
  },
  {
    cambioDirecao: 'DIRECAO',
    descricao: 'BUCHA CX DIREÇÃO UNO/PREMIO/ELBA ',
    referencia: '10119',
    marca: 'KIT & CIA',
    arqImagem: '10119.jpg',
  },
  {
    cambioDirecao: 'DIRECAO',
    descricao: 'BUCHA CX DIREÇÃO PALIO ',
    referencia: '2704',
    marca: 'NAO CADASTRADO',
    arqImagem: '',
  },
  {
    cambioDirecao: 'DIRECAO',
    descricao: 'BUCHA CX DIREÇÃO UNO/PREMIO/ELBA ',
    referencia: 'K90608-1',
    marca: 'LIGMAX',
    arqImagem: '',
  },
  {
    cambioDirecao: 'DIRECAO',
    descricao: 'BUCHA CX DIREÇÃO PALIO 21,5x30',
    referencia: 'IF26',
    marca: 'NAO CADASTRADO',
    arqImagem: 'IF26.jpg',
  },
  {
    cambioDirecao: 'DIRECAO',
    descricao: 'BUCHA CX DIREÇÃO CORSA/CELTA DHB',
    referencia: '4043',
    marca: 'SPAREKITS',
    arqImagem: '4043.jpg',
  },
  {
    cambioDirecao: 'DIRECAO',
    descricao: 'BUCHA CX DIREÇAO GOL ',
    referencia: 'WV32',
    marca: '',
    arqImagem: 'WV32.jpg',
  },
  {
    cambioDirecao: 'DIRECAO',
    descricao: 'BUCHA CX DIREÇÃO UNO/PREMIO/ELBA ',
    referencia: 'MDRP002',
    marca: '',
    arqImagem: '10119.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ARTICULAÇAO ENGATE MARCHAS CORSA/ASTRA (ferro)',
    referencia: 'DR20027',
    marca: '',
    arqImagem: 'DR200180.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ARTICULAÇAO ENGATE MARCHAS CORSA/ASTRA (plastico)',
    referencia: 'DR200180',
    marca: '',
    arqImagem: 'DR200180.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT ARTICULADOR CABO MARCHA AGILE/MONTANA ',
    referencia: 'DR20096',
    marca: '',
    arqImagem: 'DR20096.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'BUCHA VARAO TRAMBULADOR CORSA/CELTA/ASTRA ',
    referencia: '30075',
    marca: '',
    arqImagem: '30075.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT BUCHA ARTICULAÇAO CAMBIO CORSA/ASTRA ',
    referencia: 'DR20011',
    marca: '',
    arqImagem: 'DR20011.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT BUCHA ARTICULAÇAO CAMBIO CORSA/ASTRA ',
    referencia: '30345',
    marca: '',
    arqImagem: '30345.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT BUCHA ARTICULAÇAO CAMBIO CORSA/ASTRA ',
    referencia: 'AF317',
    marca: 'mundial auto pecas',
    arqImagem: 'af317.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ARTICULAÇAO INF CAMBIO CORSA/CELTA/VECTRA ',
    referencia: 'DR20012',
    marca: '',
    arqImagem: 'DR20012.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'PINO ALAVANCA CAMBIO CORSA/PRISMA/ASTRA ',
    referencia: 'LF10472P',
    marca: '',
    arqImagem: 'LF10472P.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'PINO ALAVANCA CAMBIO CORSA/PRISMA/ASTRA ',
    referencia: 'DR200140',
    marca: '',
    arqImagem: 'LF10472P.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'SUPORTE TRAMBULADOR C/ROLAMENTO UNO/ELBA ',
    referencia: 'EP2519',
    marca: 'spareKits',
    arqImagem: '2519.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'MANCAL ALAVANCA MARCHAS CORSA/ASTRA/ZAFIRA ',
    referencia: 'DR200208',
    marca: 'DR Auto Parts',
    arqImagem: 'DR20023.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT ALAVANCA CAMBIO CORSA/PRISMA/ASTRA ',
    referencia: 'DR20021',
    marca: '',
    arqImagem: 'DR20021.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT BUCHAS CABO MARCHA CORSA/CELTA/ZAFIRA ',
    referencia: 'DR20071',
    marca: '',
    arqImagem: 'DR20071.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT BUCHAS CABO MARCHA CORSA/CELTA/ZAFIRA ',
    referencia: 'DR200107',
    marca: '',
    arqImagem: 'DR200107.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT BUCHAS CABO MARCHA CORSA/CELTA/ZAFIRA ',
    referencia: 'DR20065',
    marca: '',
    arqImagem: 'DR20065.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT REPARO CABO COMANDO CORSA ',
    referencia: 'AF366K',
    marca: '',
    arqImagem: 'AF366K.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'REPARO CABO ENGATE/SELEÇAO CORSA/CELTA ',
    referencia: 'ABD33720',
    marca: '',
    arqImagem: 'ABD33720.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT TRAMBULADOR CORSA 94/ C/LIAME (20mm)',
    referencia: '30419',
    marca: '',
    arqImagem: '30419.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT TRAMBULADOR CORSA/MERIVA/MONTANA (17mm)',
    referencia: '30074',
    marca: '',
    arqImagem: '30419.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT TRAMBULADOR CORSA/MERIVA/MONTANA S/L ',
    referencia: '4036',
    marca: '',
    arqImagem: 'sparekits-4036.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'LIAME TRAMBULADOR CORSA/MONTANA 04/06 ',
    referencia: 'DR290900',
    marca: '',
    arqImagem: '',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT TRAMBULADOR/CAMBIO UNO 92/... ',
    referencia: '10387',
    marca: '',
    arqImagem: '10387.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT REPARO TRAMBULADOR GOL /94 4 MARCHAS ',
    referencia: '101806/1',
    marca: '',
    arqImagem: '1018061.PNG',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT REPARO TRAMBULADOR GOL 95/ 5 MARCHAS ',
    referencia: '101807/1',
    marca: '',
    arqImagem: '1018071.PNG',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT REPARO TRAMBULADOR GOL 95/ 5 MARCHAS ',
    referencia: 'K80309-1',
    marca: '',
    arqImagem: '',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT ALAVANCA SELETORA UNO TDS ',
    referencia: 'WK1001/EP2080(02008)',
    marca: '',
    arqImagem: 'ep2080.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ROTULA ALAVANCA CAMBIO GOL (FERRO/C/BICO) ',
    referencia: 'DR100271',
    marca: 'DR Auto Parts',
    arqImagem: 'ABD33350.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ROTULA ALAVANCA CAMBIO GOL (FERRO/C/BICO) ',
    referencia: 'ABD33350',
    marca: '',
    arqImagem: 'ABD33350.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ROTULA ALAVANCA CAMBIO GOL (FERRO/S/BICO) ',
    referencia: '40222',
    marca: '',
    arqImagem: '40222.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ROTULA ALAVANCA CAMBIO GOL (FERRO/S/BICO) ',
    referencia: 'DR100272',
    marca: 'DR Auto Parts',
    arqImagem: '40222.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ROTULA ALAVANCA CAMBIO (ALTO) PALIO TDS ',
    referencia: 'ABD33370',
    marca: '',
    arqImagem: '',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ALAVANCA CAMBIO COMPLETA 5 MARCHAS GOL /05 ',
    referencia: '40427',
    marca: '',
    arqImagem: '40427.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ROTULA ALAVANCA CAMBIO (ALTO) PALIO TDS ',
    referencia: '132058',
    marca: '',
    arqImagem: '132058.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ROTULA ALAVANCA CAMBIO (BAIXO) PALIO TDS ',
    referencia: '2065',
    marca: '',
    arqImagem: '2065.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'ROTULA ALAVANCA CAMBIO (BAIXO) PALIO TDS ',
    referencia: '087119',
    marca: '',
    arqImagem: '2065.png',
  },

  {
    cambioDirecao: 'FEIXE MOLA',
    descricao: 'KIT REPARO FEIXE MOLA TS UNO ',
    referencia: '10153',
    marca: '',
    arqImagem: '10153.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT CAMBIO TRAMBULADOR CORSA 94/... ',
    referencia: '30189',
    marca: '',
    arqImagem: '30189.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'LIAME TRAMBULADOR C/HASTE CORSA/CELTA TDS ',
    referencia: 'WK3045',
    marca: '',
    arqImagem: 'wk3045.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'LIAME TRAMBULADOR CORSA/CELTA/MONTANA ',
    referencia: '30045',
    marca: '',
    arqImagem: '30045.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'LIAME TRAMBULADOR MONZA TDS ',
    referencia: 'EP4038',
    marca: 'spareKits',
    arqImagem: '4038.png',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'LIAME TRAMBULADOR MONZA TDS ',
    referencia: '30501',
    marca: '',
    arqImagem: '30501.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'TRAMBULADOR COMPLETO GOL/PARATI/SANTANA /94 ',
    referencia: '41327',
    marca: '',
    arqImagem: '41327.jpg',
  },
  {
    cambioDirecao: 'CAMBIO',
    descricao: 'KIT TRAMBULADOR GOL/SAVEIRO/VOYAGE G5/G6',
    referencia: '40630',
    marca: 'kit&cia',
    arqImagem: '40630.jpg',
  },
  {
    cambioDirecao: 'direcao',
    descricao: 'bucha caixa de direcao mecanica gol g5 g6 fox 04/14',
    referencia: '40678',
    marca: 'kit&cia',
    arqImagem: '40678.jpg',
  },
  {
    cambioDirecao: 'DIRECAO',
    descricao: 'BUCHA CAIXA DIREÇÃO GOL G1/G2 ',
    referencia: '41316',
    marca: 'kit&cia',
    arqImagem: '41316.jpg',
  },
  
]